# Generated by Django 3.0.8 on 2020-10-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_headphones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headphones',
        ),
    ]
