# Generated by Django 3.0.8 on 2020-12-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_notebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
